name: Linter check

on: [ push,pull_request ]

jobs:
  lint-add-format:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set-up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version:${{ matrix.python-version }}

      - name: Install RUFF
        run: pip install ruff==0.4.4

      - name: Run Linter check
        run: ruff check .

      - name: Run formatter check
        run: ruff checkout --check

