name: Linter check

on: [ push,pull_request ]

jobs:
  lint-add-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
    permissions:
      contents: read

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set-up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install RUFF
        run: pip install ruff==0.4.4

      - name: Run Linter check
        run: ruff check .

      - name: Run formatter check
        run: ruff checkout --check .

